# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: gravitee.io/v1alpha1
kind: Application
metadata:
  name: backend-to-backend-application
spec:
  contextRef:
    name: "dev-ctx"
  name: "backend-to-backend-application"
  description: "OAuth settings for machine to machine interaction"
  domain: "https://example.com"
  settings:
    oauth:
      applicationType: BACKEND_TO_BACKEND
      redirectUris:
        - "https://example.com"
      grantTypes:
        - "client_credentials"
  metadata:
    - name: "test metadata 1"
      format: DATE
