apiVersion: v2
appVersion: 4.11.0-rc
version: 4.11.0-rc
kubeVersion: ">=1.18.0-0"
type: application
name: gko
description: The Gravitee Kubernetes Operator Helm Chart
icon: https://avatars2.githubusercontent.com/u/12655666?s=200&v=4
home: https://gravitee.io
sources:
  - https://github.com/gravitee-io/gravitee-kubernetes-operator
keywords:
  - gravitee.io
  - kubernetes
  - operator
  - API management
