# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
    gravitee.io/operator.version: 4.7.9-alpha
  name: sharedpolicygroups.gravitee.io
spec:
  group: gravitee.io
  names:
    kind: SharedPolicyGroup
    listKind: SharedPolicyGroupList
    plural: sharedpolicygroups
    shortNames:
      - sharedpolicygroups
    singular: sharedpolicygroup
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.name
          name: name
          type: string
        - jsonPath: .spec.description
          name: description
          type: string
        - jsonPath: .spec.apiType
          name: apiType
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: SharedPolicyGroup
          properties:
            apiVersion:
              description: |-
                APIVersion defines the versioned schema of this representation of an object.
                Servers should convert recognized schemas to the latest internal value, and
                may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
              type: string
            kind:
              description: |-
                Kind is a string value representing the REST resource this object represents.
                Servers may infer this from the endpoint the client submits requests to.
                Cannot be updated.
                In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
              type: string
            metadata:
              type: object
            spec:
              description: SharedPolicyGroupSpec
              properties:
                apiType:
                  description: Specify the SharedPolicyGroup ApiType
                  enum:
                    - MESSAGE
                    - PROXY
                    - NATIVE
                  type: string
                contextRef:
                  properties:
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                  required:
                    - name
                  type: object
                crossId:
                  description: CrossID to export SharedPolicyGroup into different environments
                  type: string
                description:
                  description: SharedPolicyGroup description
                  type: string
                name:
                  description: SharedPolicyGroup name
                  type: string
                phase:
                  description: SharedPolicyGroup phase
                    (REQUEST;RESPONSE;INTERACT;CONNECT;PUBLISH;SUBSCRIBE)
                  enum:
                    - REQUEST
                    - RESPONSE
                    - INTERACT
                    - CONNECT
                    - PUBLISH
                    - SUBSCRIBE
                  type: string
                prerequisiteMessage:
                  description: SharedPolicyGroup prerequisite Message
                  type: string
                steps:
                  description: SharedPolicyGroup Steps
                  items:
                    properties:
                      condition:
                        description: FlowStep condition
                        type: string
                      configuration:
                        description: FlowStep configuration is a map of arbitrary key-values
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      description:
                        description: FlowStep description
                        type: string
                      enabled:
                        default: true
                        description: Indicate if this FlowStep is enabled or not
                        type: boolean
                      name:
                        description: FlowStep name
                        type: string
                      policy:
                        description: FlowStep policy
                        type: string
                    required:
                      - enabled
                    type: object
                  type: array
              required:
                - apiType
                - contextRef
                - name
                - phase
              type: object
            status:
              description: SharedPolicyGroupSpecStatus defines the observed state of an API
                Context.
              properties:
                crossId:
                  description: The Cross ID is used to identify an SharedPolicyGroup that has been
                    promoted from one environment to another.
                  type: string
                environmentId:
                  description: The environment ID, if a management context has been defined to
                    sync with an APIM instance
                  type: string
                errors:
                  description: >-
                    When SharedPolicyGroup has been created regardless of
                    errors, this field is

                    used to persist the error message encountered during
                    admission
                  properties:
                    severe:
                      description: >-
                        severe errors do not pass admission and will block
                        reconcile

                        hence, this field should always be during the admission
                        phase

                        and is very unlikely to be persisted in the status
                      items:
                        type: string
                      type: array
                    warning:
                      description: >-
                        warning errors do not block object reconciliation,

                        most of the time because the value is ignored or
                        defaulted

                        when the API gets synced with APIM
                      items:
                        type: string
                      type: array
                  type: object
                id:
                  description: The ID is used to identify an SharedPolicyGroup which is unique in
                    any environment.
                  type: string
                organizationId:
                  description: The organization ID, if a management context has been defined to
                    sync with an APIM instance
                  type: string
                processingStatus:
                  description: >-
                    The processing status of the SharedPolicyGroup.

                    The value is `Completed` if the sync with APIM succeeded,
                    Failed otherwise.
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
